language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
addons:
  apt:
    packages:
      - python3-pip
env:
  global:
    - PYTHON=python3
matrix:
  allow_failures:
    - julia: nightly
git:
    depth: 1
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';