language: julia
os:
  - linux
dist: xenial
sudo: true
julia:
  - 1.0
  - 1.1
  - nightly
addons:
  apt:
    packages:
      - python3-setuptools
      - python3-pip
      - python3-wheel
env:
  global:
    - PYTHON=python3
matrix:
  allow_failures:
    - julia: nightly
git:
    depth: 1
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("GAlgebra")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ -e 'using Pkg; Pkg.build("GAlgebra")'
        - julia --project=docs/ docs/make.jl
      after_success: skip