name = "GAlgebra"
uuid = "ace2154a-7c42-11e9-15a2-c13a55fc59e4"
authors = ["Utensil Song"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
PyCall = "1.96"
SymPy = "2.0"
julia = "1.10"

[extras]
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SymPy"]
