name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.0.4, 1.1.1]
        os: [ubuntu-latest]
        python: [ '3.x' ]
        project: ['GAlgebra']
    
    steps:
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v0.2
        with:
          version: ${{ matrix.julia-version }}
      - name: "Check out"
        uses: actions/checkout@v1.0.0
      - name: "Test"
        run: |
          julia --project=@. -e "using Pkg; Pkg.instantiate();"
          julia --project=@. -e "using Pkg; Pkg.build(\"${{ matrix.project }}\");"
          julia --project=@. -e "using Pkg; Pkg.test(\"${{ matrix.project }}\", coverage=true);"
      - name: "Coverage"
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
        if: success()
